### ISSUE TITLE
Empty report when running with pytest-xdist

### ISSUE THREAD

**Issue by orsinium** [bloomberg/pytest-memray#2]
## Bug Report

**Current Behavior** The plugin produces an empty output when running tests with [pytest-xdist](https://github.com/pytest-dev/pytest-xdist).

**Input Code**

```python
a = []

def something():
    for i in range(10_000):
        a.append(i)

def test_something():
    something()
```
Running multiple processes:

![image](https://user-images.githubusercontent.com/9638362/164390453-58633538-c132-48e5-8d25-6983084808d4.png)

Running without distribution:

![image](https://user-images.githubusercontent.com/9638362/164390513-de195022-a765-47f6-9c8a-f0b18210a33c.png)

**Environment**

- Python(s): python3.9, pytest-xdist, pytest-memray

**Possible-solutions**: For the beginning, it would be sufficient to detect running tests with pytest-xdist and warn the user that `-n0` is required to make pytest-memray work. Of course, moving forward, it would be great to make both plugins work together. Running tests in a single process is too hardcore for some projects.

**Comment by gaborbernat** [comment]
Is there a way we can instead add support for xdist?

**Comment by pablogsal** [comment]
> Is there a way we can instead add support for xdist?

Yes, but is not trivial. The problem is that currently the information is collected by every worker but the process that is orchestrating the build is the want printing of the summary and when is going done it finds no information because the workers are not sending the information back. Another problem is that we should not leave the result files lying around until the full test suite finishes because it may be a lot of data (currently we delete the files after every test finishes so they never pile up).

**Comment by gaborbernat** [comment]
I'm fine with displaying a usage error for now and nudge to `-n1`. Just would like another issue open that handles support for that.

**Comment by petr-tik** [comment]
> I'm fine with displaying a usage error for now and nudge to -n1

I will add a test and code for the `ExitCode.UsageError` then

**Comment by orsinium** [comment]
> I'm fine with displaying a usage error for now and nudge to -n1

A minor correction: it should be `-n0`. AFAIK, `-n1` will run with the distribution but with just one worker. `-n0` will disable pytest-xdist altogether.
