### ISSUE TITLE
Support flag `--trace-python-allocators` when running the memray pytest plugin

### ISSUE THREAD

**Issue by godiedelrio** [bloomberg/pytest-memray#78]
## Feature Request

**Is your feature request related to a problem? Please describe.**
I've read through the [doc](https://bloomberg.github.io/memray/python_allocators.html) about how `pymalloc` affects profiling results.
It seems that when running a test suite using the memray pytest plugin, not all the memory allocations from a test would be reported if the pymalloc allocator finds memory available in the arenas and memory pools that had been previously allocated by the tests in the test suite that ran before. Is this something that might happen?

**Describe the solution you'd like**
In such a case, would help if the pytest memray plugin could be run with the option `--trace-python-allocators` to always track the calls to the pymalloc memory allocator?

**Comment by pablogsal** [comment]
> not all the memory allocations from a test would be reported

Well, this depends on what you define as "memory allocations". Take into account that in a real program you will not run without `pymalloc` so you will not allocate memory from the system allocator for each Python object. At the same time, memory *is* getting allocated when arenas are allocated, is just that this happens in a different fashion.

In any case, I do agree that because no report is intrinsically better than the other, it makes sense to expose this flag.

Are you interested on making a PR? Otherwise @gaborbernat. @godlygeek  or myself we can get to this eventually :)
